{
 "title": "WSO2 Streaming Integrator App Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_stream_throughput_total, app)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Inputs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_total_reads{app=~\"$app\", type=~\"file|cdc\"}) "
    }
   ]
  },
  {
   "title": "(Inputs/Outputs)/Sec",
   "type": "graph",
   "gridPos": { "h": 14, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (rate(siddhi_total_reads{app=~\"$app\"}[$__interval]))",
     "legendFormat": "Inputs"
    },
    {
     "expr": "sum by (app) (rate(siddhi_total_writes{app=~\"$app\"}[$__interval]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Inputs/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(siddhi_total_reads{app=~\"$app\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Outputs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_total_writes{app=~\"$app\", type=~\"file|rdbms\"})"
    }
   ]
  },
  {
   "title": "Outputs/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(siddhi_total_writes{app=~\"$app\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Transport Level Errors",
   "type": "singlestat",
   "description": "Total errors occurred while consuming & publishing events",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(siddhi_store_rdbms_total_error_count{app=~\"$app\"}) or vector(0)) + (sum(siddhi_file_source_error_count{app=~\"$app\"}) or vector(0)) + (sum(siddhi_cdc_source_listening_mode_total_error_count{app=~\"$app\"}) or vector(0)) + (sum(siddhi_cdc_source_polling_mode_total_error_count{app=~\"$app\"}) or vector(0)) + (sum(siddhi_file_sink_total_error_count{app=~\"$app\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Mapping Errors",
   "type": "singlestat",
   "description": "Number of dropped events due to invalid mapping.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(siddhi_total_reads{app=~\"$app\", type=~\"file|cdc\"}) or vector(0)) - ((sum(siddhi_file_source_total_valid_events_count{app=~\"$app\"}) or vector(0)) + (sum(siddhi_cdc_source_listening_mode_total_valid_events_count{app=~\"$app\"}) or vector(0)) +(sum(siddhi_cdc_source_polling_mode_total_valid_events_count{app=~\"$app\"}) or vector(0))) "
    }
   ]
  },
  { "title": "Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "<h2><center>File</center></h2>\n"
  },
  {
   "title": "File Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(siddhi_file_source_event_count{app=~\"$app\"}) by (file_name, mode, stream_name, file_path, app)"
    },
    {
     "expr": "sum(siddhi_file_source_file_size{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_source_file_status{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_source_elapse_time{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_source_started_time{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum((siddhi_file_source_event_count{app=~\"$app\"} - ignoring(file_name, mode, stream_name)siddhi_file_source_total_valid_events_count{app=~\"$app\"}) + siddhi_file_source_error_count{app=~\"$app\"}) by (file_path)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "content": "\n<h2><center>CDC</center></h2>\n"
  },
  {
   "title": "CDC Streaming Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_event_count{app=~\"$app\"}) by (db_url, A_db_type, C_database, D_tablename, B_host, app)"
    },
    {
     "expr": "sum(rate(siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\"}[1m])) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_db_status{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_idle_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_last_receive_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\"} - ignoring(tablename)siddhi_cdc_source_listening_mode_total_valid_events_count{app=~\"$app\"} + siddhi_cdc_source_listening_mode_total_error_count{app=~\"$app\"}) by (db_url)"
    }
   ]
  },
  {
   "title": "CDC Scheduled Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\"}) by (db_url, A_db_type, C_database, D_tablename, B_host, app)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_events_in_last_polling_interval{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_db_status{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_idle_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_last_receive_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\"} - ignoring(A_db_type, B_host, C_database, D_tablename)siddhi_cdc_source_polling_mode_total_valid_events_count{app=~\"$app\"} + siddhi_cdc_source_polling_mode_total_error_count{app=~\"$app\"}) by (db_url)"
    }
   ]
  },
  { "title": "Destinations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "content": "\n<h2><center>File</center></h2>\n"
  },
  {
   "title": "File Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(siddhi_file_sink_event_count{app=~\"$app\"}) by (file_name, mode, stream_name, file_path,app)"
    },
    {
     "expr": "sum(siddhi_file_sink_file_size{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_file_status{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_lines_count{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_elapsed_time{app=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_total_error_count{app=~\"$app\"} + siddhi_file_sink_dropped_events{app=~\"$app\"} ) by (file_path)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 },
   "content": "\n<h2><center>RDBMS</center></h2>\n"
  },
  {
   "title": "RDBMS Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(siddhi_store_rdbms_total_writes{app=~\"$app\"}) by (db_url, A_db_type, C_database, D_tablename, B_shortenUrl, app)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_db_status{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_idle_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_processing_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_last_change_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_total_error_count{app=~\"$app\"}) by (db_url)"
    }
   ]
  }
 ]
}