{
 "title": "WSO2 Streaming Integration Overall Statistics",
 "tags": [
  "wso2",
  "prometheus",
  "siddhi",
  "streaming-integration"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Appname",
    "query": "label_values(siddhi_stream_throughput_total, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Inputs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_total_reads{type=~\"cdc|file\"}) "
    }
   ]
  },
  {
   "title": "Overview Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(siddhi_total_reads{type=~\"cdc|file\"}) by (app)"
    },
    {
     "expr": "sum by(app) (rate(siddhi_total_reads{type=~\"cdc|file\"}[$__interval]))"
    },
    {
     "expr": "sum(siddhi_total_writes{type=~\"rdbms|file\"}) by (app)"
    },
    {
     "expr": "sum (rate(siddhi_total_writes{type=~\"rdbms|file\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Outputs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_total_writes{type=~\"rdbms|file\"})"
    }
   ]
  },
  {
   "title": "(Consume/Publish)/Sec",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(siddhi_total_reads{type=~\"cdc|file\"}[$__interval]))",
     "legendFormat": "Inputs"
    },
    {
     "expr": "sum(rate(siddhi_total_writes{type=~\"file|rdbms\"}[$__interval]))",
     "legendFormat": "Outputs"
    }
   ]
  }
 ]
}