{
 "title": "WSO2 Streaming Integrator - Kafka Sink Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_stream_throughput_total, app)"
   },
   {
    "name": "stream_id",
    "label": "Stream Name",
    "query": "label_values(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\"}, stream_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Writes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "siddhi_kafka_sink_write_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}"
    }
   ]
  },
  {
   "title": "Received Events/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Events/Sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}[5m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Outputs/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Last committed offset",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "siddhi_kafka_sink_current_offset"
    }
   ]
  },
  {
   "title": "Transport Level Errors",
   "type": "singlestat",
   "description": "Total errors occurred while consuming events",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(siddhi_kafka_sink_error_count_without_partition{app=~\"$app\",stream_id=~\"$stream_id\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Ack Delay Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_sink_per_stream_last_message_latency_in_millis{app=~\"$app\",stream_id=~\"$stream_id\"}[5m]))",
     "legendFormat": "Ack Delay in seconds"
    }
   ]
  },
  {
   "title": "Kafka Sink Statistics",
   "type": "table",
   "description": "Each stream in a siddhi app creates a unique consumer. This table shows the stats per each consumer (stream ID)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(siddhi_kafka_sink_current_offset{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition)"
    },
    {
     "expr": "sum(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition)"
    },
    {
     "expr": "sum(rate(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}[1h])) by (topic,partition)"
    },
    {
     "expr": "avg(siddhi_kafka_sink_per_stream_last_message_size_in_bytes{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition)"
    },
    {
     "expr": "avg(siddhi_kafka_sink_per_stream_last_message_latency_in_millis{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition)"
    },
    {
     "expr": "sum(siddhi_kafka_sink_error_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition)"
    },
    {
     "expr": "(sum(siddhi_kafka_sink_error_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition) / sum(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition))"
    },
    {
     "expr": "sum(siddhi_kafka_sink_per_stream_last_message_published_at{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition)"
    }
   ]
  }
 ]
}