{
 "title": "WSO2 Streaming Integrator - Kafka Source Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_stream_throughput_total, app)"
   },
   {
    "name": "stream_id",
    "label": "Stream Name",
    "query": "label_values(siddhi_kafka_source_read_count_per_stream{app=~\"$app\"}, stream_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Reads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "siddhi_kafka_source_read_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}"
    }
   ]
  },
  {
   "title": "Received Events/Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Events/Sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_source_read_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}[5m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Inputs/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_source_read_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Transport Level Errors",
   "type": "singlestat",
   "description": "Total errors occurred while consuming events",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(siddhi_kafka_source_error_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Consumer Lag Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_source_per_stream_with_partition_consumer_lag{app=~\"$app\",stream_id=~\"$stream_id\"}[5m]))",
     "legendFormat": "Lag in seconds"
    }
   ]
  },
  {
   "title": "Statistics by Partition",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(siddhi_kafka_source_read_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition,group_id)"
    },
    {
     "expr": "sum by (topic,partition,group_id)(rate(siddhi_kafka_source_read_count_per_stream{app=~\"$app\",stream_id=~\"$stream_id\"}[1h]))"
    },
    {
     "expr": "sum(siddhi_kafka_source_current_offset{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition,group_id)"
    },
    {
     "expr": "sum(siddhi_kafka_source_per_stream_last_message_consumed_at{app=~\"$app\",stream_id=~\"$stream_id\"}) by (topic,partition,group_id)"
    },
    {
     "expr": "sum(siddhi_kafka_source_error_count_per_stream{app=~\"$app\",topic=~\"$topic\",stream_id=~\"$stream_id\"}) by (topic,partition,group_id)"
    }
   ]
  }
 ]
}