{
 "title": "WSO2 Streaming Integrator - Kafka Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_stream_throughput_total, app)"
   }
  ]
 },
 "panels": [
  { "title": "Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Reads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_kafka_source_read_count_per_stream{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Received Events/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_source_read_count_per_stream{app=~\"$app\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Inputs/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_source_read_count_per_stream{app=~\"$app\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Transport Level Errors",
   "type": "singlestat",
   "description": "Total errors occurred while consuming events",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(siddhi_kafka_source_error_count_per_stream{app=~\"$app\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Kafka Source Statistics",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(siddhi_kafka_source_read_count_per_stream{app=~\"$app\"}) by (stream_id)"
    },
    {
     "expr": "sum(rate(siddhi_kafka_source_read_count_per_stream{app=~\"$app\"}[1h])) by (stream_id)"
    },
    {
     "expr": "sum(siddhi_kafka_source_per_stream_last_message_consumed_at{app=~\"$app\"}) by (stream_id)"
    },
    {
     "expr": "sum(siddhi_kafka_source_per_stream_with_partition_consumer_lag{app=~\"$app\"}) by (stream_id) / 1000"
    },
    {
     "expr": "sum(siddhi_kafka_source_error_count_per_stream{app=~\"$app\"}) by (stream_id)"
    }
   ]
  },
  {
   "title": "Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "Total Writes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "siddhi_kafka_sink_write_count_per_stream{app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Published Events/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\"}[5m])) by (topic)",
     "legendFormat": "Received Events"
    }
   ]
  },
  {
   "title": "Outputs/Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Transport Level Errors",
   "type": "singlestat",
   "description": "Total errors occurred while consuming events",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(siddhi_kafka_sink_error_count_without_partition{app=~\"$app\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Kafka Sink Statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(siddhi_kafka_sink_current_offset{app=~\"$app\"}) by (stream_id)"
    },
    {
     "expr": "sum(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\"}) by (stream_id)"
    },
    {
     "expr": "sum(rate(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\"}[1h])) by (stream_id)"
    },
    {
     "expr": "avg(siddhi_kafka_sink_per_stream_last_message_size_in_bytes{app=~\"$app\"}) by (stream_id)"
    },
    {
     "expr": "avg(siddhi_kafka_sink_per_stream_last_message_latency_in_millis{app=~\"$app\"}) by (stream_id)"
    },
    {
     "expr": "sum(siddhi_kafka_sink_error_count_without_partition{app=~\"$app\"}) by (stream_id) "
    },
    {
     "expr": "(sum(siddhi_kafka_sink_error_count_without_partition{app=~\"$app\"}) by (stream_id) / sum(siddhi_kafka_sink_write_count_per_stream{app=~\"$app\"}) by (stream_id)) "
    },
    {
     "expr": "sum(siddhi_kafka_sink_per_stream_last_message_published_at{app=~\"$app\"}) by (stream_id)"
    }
   ]
  }
 ]
}