{
 "title": "WSO2 Streaming Integrator - HTTP Sink Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_http_apps, app)"
   },
   {
    "name": "url",
    "label": "URL",
    "query": "label_values(siddhi_http_sink_event_count{app=~\"$app\"}, url)"
   }
  ]
 },
 "panels": [
  { "title": "$url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "url" },
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(siddhi_http_sink_status{app=~\"$app\", url=~\"$url\"})"
    }
   ]
  },
  {
   "title": "Success Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_http_sink_event_count{app=~\"$app\", url=~\"$url\"}) - (sum(siddhi_http_sink_error_count{app=~\"$app\", url=~\"$url\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_http_sink_event_count{app=~\"$app\", url=~\"$url\"})"
    }
   ]
  },
  {
   "title": "Failed Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_http_sink_error_count{app=~\"$app\", url=~\"$url\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Average Request Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_http_sink_request_size{app=~\"$app\", url=~\"$url\"}) / sum(siddhi_http_sink_event_count{app=~\"$app\", url=~\"$url\"})"
    }
   ]
  },
  {
   "title": "Last successful event published at",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "dateTimeAsUSNoDateIfToday",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_http_sink_last_event_time{app=~\"$app\", url=~\"$url\"})"
    }
   ]
  },
  {
   "title": "Successful Requests Percentage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(siddhi_http_sink_event_count{app=~\"$app\", url=~\"$url\"}) - (sum(siddhi_http_sink_error_count{app=~\"$app\", url=~\"$url\"}) or vector(0))) / sum(siddhi_http_sink_event_count{app=~\"$app\", url=~\"$url\"}) * 100"
    }
   ]
  },
  {
   "title": "Sent Events/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_http_sink_event_count{app=~\"$app\", url=~\"$url\"}[1m])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Request Size/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_http_sink_event_count{app=~\"$app\", url=~\"$url\"}[1m])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_http_sink_average_latency{app=~\"$app\", url=~\"$url\"}[1m])",
     "legendFormat": "{{url}}"
    }
   ]
  }
 ]
}