{
 "title": "WSO2 Streaming Integration - File Source Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_file_apps, app_name)"
   },
   {
    "name": "source",
    "label": "Files",
    "query": "label_values(siddhi_file_source_event_count{app_name=~\"$app\"}, file_path)"
   }
  ]
 },
 "panels": [
  { "title": "$source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "source" },
  {
   "title": "File Status",
   "type": "singlestat",
   "description": "Showing the stream status of file. Available status:  `Consuming`, `Completed`. 'Idle' status only available when the file is reading while tailing enabled.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_file_status{app_name=~\"$app\", file_path=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Read Lines",
   "type": "singlestat",
   "description": "The number of Lines available in the `$source` file.",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_lines_count{app_name=~\"$app\", file_path=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Successful Reads",
   "type": "singlestat",
   "description": "Number of Events that were read successfully.",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_event_count{app_name=~\"$app\", file_path=~\"$source\"} "
    }
   ]
  },
  {
   "title": "Processed",
   "type": "singlestat",
   "description": "Processed byte size of `$source` file up to now.",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_total_read_byte{app_name=~\"$app\", file_path=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Successful Reads Percentage",
   "type": "gauge",
   "description": "Percentage of \"Successful Reads/Total Reads\"",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "siddhi_file_source_event_count{app_name=~\"$app\", file_path=~\"$source\"} / ignoring(app_name, file_name, stream_name, mode) (siddhi_file_source_event_count{app_name=~\"$app\", file_path=~\"$source\"} + ignoring(app_name, file_name, stream_name, mode) siddhi_file_source_dropped_events{app_name=~\"$app\", file_path=~\"$source\"}) * 100"
    }
   ]
  },
  {
   "title": "Dropped Events",
   "type": "singlestat",
   "description": "Number of Events that were dropped while reading.",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_dropped_events{file_path=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "(siddhi_file_source_read_percentage{app_name=~\"$app\", file_path=~\"$source\"}) * (siddhi_file_source_tailing_enable{app_name=~\"$app\", file_path=~\"$source\"} - 1) * -1"
    }
   ]
  },
  {
   "title": "Events per Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_event_count{app_name=~\"$app\", file_path=~\"$source\"} / ignoring(mode,stream_name, file_name)siddhi_file_source_elapse_time{app_name=~\"$app\", file_path=~\"$source\"} * 1000"
    }
   ]
  },
  {
   "title": "Read Bytes per Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_total_read_byte{app_name=~\"$app\", file_path=~\"$source\"} / siddhi_file_source_elapse_time{} * 1000"
    }
   ]
  },
  {
   "title": "Elapase Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_elapse_time{app_name=~\"$app\", file_path=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Started Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_started_time{app_name=~\"$app\", file_path=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Completed Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_source_completed_time{app_name=~\"$app\", file_path=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Events/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_file_source_event_count{app_name=~\"$app\", file_path=~\"$source\"}[1m])",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "KB/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_file_source_total_read_byte{app_name=~\"$app\", file_path=~\"$source\"}[1m])",
     "legendFormat": "KB"
    }
   ]
  }
 ]
}