{
 "title": "WSO2 Streaming Integration - File Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_file_apps, app_name)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(siddhi_file_source_event_count{app_name=~\"$app\"}, file_path)"
   },
   {
    "name": "sink",
    "label": "Sink",
    "query": "label_values(siddhi_file_sink_event_count{app_name=~\"$app\"}, file_path)"
   }
  ]
 },
 "panels": [
  { "title": "Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_source_event_count{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "File Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(siddhi_file_source_event_count{app_name=~\"$app\"}) by (file_name, mode, stream_name, file_path)"
    },
    {
     "expr": "sum(siddhi_file_source_file_size{app_name=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_source_file_status{app_name=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_source_elapse_time{app_name=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_source_started_time{app_name=~\"$app\"}) by (file_path)"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_source_file_status{app_name=~\"$app\"} >= 2)"
    }
   ]
  },
  {
   "title": "In Progress",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_source_file_status{app_name=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Total Events Received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(siddhi_file_source_event_count{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Received Events/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_file_source_event_count{app_name=~\"$app\"}[1m])",
     "legendFormat": "{{file_name}}"
    }
   ]
  },
  { "title": "Sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Files",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_sink_event_count{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "File Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "sum(siddhi_file_sink_event_count{app_name=~\"$app\"}) by (file_name, mode, stream_name, file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_file_size{app_name=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_file_status{app_name=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_lines_count{app_name=~\"$app\"}) by (file_path)"
    },
    {
     "expr": "sum(siddhi_file_sink_elapsed_time{app_name=~\"$app\"}) by (file_path)"
    }
   ]
  },
  {
   "title": "Publishing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_sink_file_status{app_name=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_sink_file_status{app_name=~\"$app\"} == 3)"
    }
   ]
  },
  {
   "title": "Published Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(siddhi_file_sink_event_count{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Published Events/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_file_sink_event_count{app_name=~\"$app\"}[1m])",
     "legendFormat": "{{file_name}}"
    }
   ]
  },
  { "title": "File Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "content": "\n<h1><center>Delete</center></h1>\n\n\n\n"
  },
  {
   "title": "Total Deletion",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_delete{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Deleted Files",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "sum(siddhi_file_delete{app_name=~\"$app\"}) by (_source, time)"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 45 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_delete{app_name=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 45 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_delete{app_name=~\"$app\"} == 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "content": "\n<h1><center>Move</center></h1>\n\n\n\n"
  },
  {
   "title": "Total Moved",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 50 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_move{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Moved Files",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "sum(siddhi_file_move{app_name=~\"$app\"}) by (_source, time, destination)"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 54 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_move{app_name=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 54 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_move{app_name=~\"$app\"} == 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "content": "\n<h1><center>Copy</center></h1>\n\n\n\n"
  },
  {
   "title": "Total Copied",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 59 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_copy{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Copied Files",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 59 },
   "targets": [
    {
     "expr": "sum(siddhi_file_copy{app_name=~\"$app\"}) by (_source, time, destination)"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_copy{app_name=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_copy{app_name=~\"$app\"} == 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 66 },
   "content": "\n<h1><center>Archive</center></h1>\n\n\n\n"
  },
  {
   "title": "Created Archived",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 68 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_archive{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Archived Files",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 68 },
   "targets": [
    {
     "expr": "sum(siddhi_file_archive{app_name=~\"$app\"}) by (_source, time, type, destination)"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_archive{app_name=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_file_archive{app_name=~\"$app\"} == 0)"
    }
   ]
  }
 ]
}