{
 "title": "WSO2 Streaming Integrator - File Sink Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_file_apps, app)"
   },
   {
    "name": "sink",
    "label": "Files",
    "query": "label_values(siddhi_file_sink_event_count{app=~\"$app\"}, file_path)"
   }
  ]
 },
 "panels": [
  { "title": "$sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sink" },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_file_status{app=~\"$app\", file_path=~\"$sink\"}"
    }
   ]
  },
  {
   "title": "Written Lines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_lines_count{app=~\"$app\", file_path=~\"$sink\"}"
    }
   ]
  },
  {
   "title": "Written Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_total_written_byte{app=~\"$app\", file_path=~\"$sink\"}"
    }
   ]
  },
  {
   "title": "Successful Writes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "siddhi_file_sink_event_count{app=~\"$app\", file_path=~\"$sink\"} / ignoring(mode, stream_name, file_name)(siddhi_file_sink_dropped_events{app=~\"$app\", file_path=~\"$sink\"} + ignoring(mode, stream_name, file_name) siddhi_file_sink_event_count{}) * 100",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "KB/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_file_sink_total_written_byte{file_path=~\"$sink\"}[1m])",
     "legendFormat": "KB"
    }
   ]
  },
  {
   "title": "Successful Writes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_event_count{app=~\"$app\", file_path=~\"$sink\"}"
    }
   ]
  },
  {
   "title": "Dropped Events",
   "type": "singlestat",
   "description": "The number of events dropped.",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_dropped_events{app=~\"$app\", file_path=~\"$sink\"} + siddhi_file_sink_total_error_count{file_path=~\"$sink\", app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Write Bytes Per Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(siddhi_file_sink_total_written_byte{app=~\"$app\", file_path=~\"$sink\"}[1m])"
    }
   ]
  },
  {
   "title": "Events Per Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(siddhi_file_sink_event_count{app=~\"$app\", file_path=~\"$sink\"}[1m])"
    }
   ]
  },
  {
   "title": "Last Event Published at",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_last_published_time{app=~\"$app\", file_path=~\"$sink\"}"
    }
   ]
  },
  {
   "title": "Elapse Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_elapsed_time{app=~\"$app\", file_path=~\"$sink\"}"
    }
   ]
  },
  {
   "title": "Client Connection Errors",
   "type": "singlestat",
   "description": "The number of errors occurred while  writing events into the file.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_total_error_count{file_path=~\"$sink\", app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Invalid events",
   "type": "singlestat",
   "description": "The number of events dropped due to invalid UTF-8 encoding.",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_file_sink_dropped_events{app=~\"$app\", file_path=~\"$sink\"} "
    }
   ]
  },
  {
   "title": "Events/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(siddhi_file_sink_event_count{file_path=~\"$sink\"}[1m])",
     "legendFormat": "Events"
    }
   ]
  }
 ]
}