{
 "title": "WSO2 Streaming Integration - CDC Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_cdc_apps, app)"
   }
  ]
 },
 "panels": [
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Tables",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_cdc_source_listening_mode_db_status{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Received Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\"}[$__interval])",
     "legendFormat": "{{tablename}}"
    }
   ]
  },
  {
   "title": "Total Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_event_count{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "CDC Streaming Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_event_count{app=~\"$app\"}) by (db_url, A_db_type, C_database, D_tablename, B_host)"
    },
    {
     "expr": "sum(rate(siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\"}[1m])) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_db_status{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_idle_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_last_receive_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\"} - ignoring(tablename)siddhi_cdc_source_listening_mode_total_valid_events_count{app=~\"$app\"} + siddhi_cdc_source_listening_mode_total_error_count{app=~\"$app\"}) by (db_url)"
    }
   ]
  },
  { "title": "Scheduled", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Tables",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_cdc_source_polling_mode_db_status{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Received Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\"}[$__interval])",
     "legendFormat": "{{tablename}}"
    }
   ]
  },
  {
   "title": "Total Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "CDC Scheduled Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\"}) by (db_url, A_db_type, C_database, D_tablename, B_host)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_events_in_last_polling_interval{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_db_status{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_idle_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_last_receive_time{app=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\"} - ignoring(A_db_type, B_host, C_database, D_tablename)siddhi_cdc_source_polling_mode_total_valid_events_count{app=~\"$app\"} + siddhi_cdc_source_polling_mode_total_error_count{app=~\"$app\"}) by (db_url)"
    }
   ]
  }
 ]
}