{
 "title": "WSO2 Streaming Integrator - CDC Scheduled Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_cdc_apps, app_name)"
   },
   {
    "name": "db_url",
    "label": "Database URL",
    "query": "label_values(siddhi_cdc_source_polling_mode_event_count{app_name=~\"$app\"}, db_url)"
   }
  ]
 },
 "panels": [
  { "title": "$db_url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "db_url" },
  {
   "title": "Total Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_event_count{app_name=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Last Change Occurred At",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_last_receive_time{app_name=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Table Status",
   "type": "singlestat",
   "description": "Showing the stream status of the Table. Available Status: `Consuming`, `Idle`, `Error`",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_db_status{db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_idle_time{app_name=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Polling Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_polling_details{app_name=~\"$app\", db_url=~\"$db_url\"}) by (_started_time, duration, status)"
    }
   ]
  },
  {
   "title": "Received Changes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(siddhi_cdc_source_polling_mode_event_count{app_name=~\"$app\", db_url=~\"$db_url\"}[1m])",
     "legendFormat": "{{tablename}}"
    }
   ]
  }
 ]
}