{
 "title": "WSO2 Streaming Integration - CDC Streaming Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_cdc_apps, app)"
   },
   {
    "name": "db_url",
    "label": "Database URL",
    "query": "label_values(siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\"}, db_url)"
   }
  ]
 },
 "panels": [
  { "title": "$db_url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "db_url" },
  {
   "title": "Total Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Total Inserts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_event_count{app=~\"$app\", db_url=~\"$db_url\", operation_type=\"Insert\"}"
    }
   ]
  },
  {
   "title": "Total Updates",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_event_count{app=~\"$app\", db_url=~\"$db_url\", operation_type=\"Update\"}"
    }
   ]
  },
  {
   "title": "Total Deletes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_event_count{app=~\"$app\", db_url=~\"$db_url\", operation_type=\"Delete\"}"
    }
   ]
  },
  {
   "title": "Last Change Occured At",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_last_receive_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Table Status",
   "type": "singlestat",
   "description": "Showing the stream status of the Table.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_db_status{db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_idle_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Mapping Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_events_per_table{app=~\"$app\", db_url=~\"$db_url\"} - ignoring(tablename)siddhi_cdc_source_listening_mode_total_valid_events_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Last Insert",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_last_receive_time_by_operation{app=~\"$app\", db_url=~\"$db_url\", operation_type=\"Insert\"}"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_last_receive_time_by_operation{app=~\"$app\", db_url=~\"$db_url\", operation_type=\"Update\"}"
    }
   ]
  },
  {
   "title": "Last Delete",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_last_receive_time_by_operation{app=~\"$app\", db_url=~\"$db_url\", operation_type=\"Delete\"}"
    }
   ]
  },
  {
   "title": "Transport Level Errors",
   "type": "singlestat",
   "description": "Number of errors occured while capturing the data from the table.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_listening_mode_total_error_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Received Changes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(siddhi_cdc_source_listening_mode_event_count{app=~\"$app\", db_url=~\"$db_url\"}[1m])",
     "legendFormat": "{{operation_type}} "
    }
   ]
  }
 ]
}