{
 "title": "WSO2 Streaming Integration - CDC Scheduled Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_cdc_apps, app)"
   },
   {
    "name": "db_url",
    "label": "Database URL",
    "query": "label_values(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\"}, db_url)"
   }
  ]
 },
 "panels": [
  { "title": "$db_url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "db_url" },
  {
   "title": "Total Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_event_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Last Change Occurred At",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_last_receive_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Table Status",
   "type": "singlestat",
   "description": "Showing the stream status of the Table. Available Status: `Consuming`, `Idle`, `Error`",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_db_status{db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_idle_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Mapping Errors",
   "type": "singlestat",
   "description": "Mapping Errors",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_event_count{app=~\"$app\", db_url=~\"$db_url\"} - ignoring(A_db_type, B_host, C_database, D_tablename)siddhi_cdc_source_polling_mode_total_valid_events_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Transport Level Errors",
   "type": "singlestat",
   "description": "Number of errors occured while capturing the data from the table.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_cdc_source_polling_mode_total_error_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Polling Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(siddhi_cdc_source_polling_mode_polling_details{app=~\"$app\", db_url=~\"$db_url\"}) by (_started_time, duration, status)"
    }
   ]
  },
  {
   "title": "Received Changes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(siddhi_cdc_source_polling_mode_event_count{app=~\"$app\", db_url=~\"$db_url\"}[1m])",
     "legendFormat": "{{D_tablename}}"
    }
   ]
  }
 ]
}