{
 "title": "WSO2 Streaming Integrator - RDBMS Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_store_rdbms_apps, app_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Tables",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(siddhi_store_rdbms_db_status{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Changed Rows",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(siddhi_store_rdbms_total_writes{app_name=~\"$app\"}[1m])",
     "legendFormat": "{{D_tablename}}"
    }
   ]
  },
  {
   "title": "Total Inserts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(siddhi_store_rdbms_insert_rows_count{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Total Updates",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(siddhi_store_rdbms_update_rows_count{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Total Deletes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(siddhi_store_rdbms_delete_rows_count{app_name=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Table Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(siddhi_store_rdbms_total_writes{app_name=~\"$app\"}) by (db_url, A_db_type, C_database, D_tablename, B_shortenUrl)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_db_status{app_name=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_idle_time{app_name=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_processing_time{app_name=~\"$app\"}) by (db_url)"
    },
    {
     "expr": "sum(siddhi_store_rdbms_last_change_time{app_name=~\"$app\"}) by (db_url)"
    }
   ]
  }
 ]
}