{
 "title": "WSO2 Streaming Integration - RDBMS Table Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App Name",
    "query": "label_values(siddhi_store_rdbms_apps, app)"
   },
   {
    "name": "db_url",
    "label": "Database URL",
    "query": "label_values(siddhi_store_rdbms_total_writes{app=~\"$app\"}, db_url)"
   }
  ]
 },
 "panels": [
  { "title": "$db_url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "db_url" },
  {
   "title": "Total Writes",
   "type": "singlestat",
   "description": "The number of changes applied to the table by executing `Insert`, `Update`, `Delete` Queries.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_total_writes{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Total Inserts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_insert_rows_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Total Updates",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_update_rows_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Total Deletes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_delete_rows_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "singlestat",
   "description": "Number of errors occured while capturing the data from the table.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_total_error_count{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Last Insert",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_last_insert_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_last_update_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Last Delete",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_last_delete_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Table Status",
   "type": "singlestat",
   "description": "`Connected` - The connection with the table has been successfully made, but no changes have been made to the table.      \n `Processing` - The table is currently doing some operations(Insert, Update, Delete)\n`Idle` - The table is currently not doing any operations",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_db_status{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "singlestat",
   "description": "This shows how long the table stays in the `Idle` mode(Without doing any CUD operations)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_idle_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Process Time",
   "type": "singlestat",
   "description": "When the `Table Status` becomes `Processing` this shows how long the table stays in the processing mode",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_processing_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Last Change Occured At",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "siddhi_store_rdbms_last_change_time{app=~\"$app\", db_url=~\"$db_url\"}"
    }
   ]
  },
  {
   "title": "Total Changes per Min",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(siddhi_store_rdbms_insert_rows_count{app=~\"$app\", db_url=~\"$db_url\"}[1m])",
     "legendFormat": "Insert"
    },
    {
     "expr": "increase(siddhi_store_rdbms_update_rows_count{app=~\"$app\", db_url=~\"$db_url\"}[1m])",
     "legendFormat": "Updates"
    },
    {
     "expr": "increase(siddhi_store_rdbms_delete_rows_count{app=~\"$app\", db_url=~\"$db_url\"}[1m])",
     "legendFormat": "Delete"
    }
   ]
  }
 ]
}